### ISSUE TITLE
Control over window styling

### ISSUE THREAD

**Issue by Advait1306** [tro1d/flutter-scrcpy-manager#1]
I can see that you are running the scrcpy command in cmd, is there a way for me to style the window which opens up in scrcpy?

**Comment by tro1d** [comment]
> I can see that you are running the scrcpy command in cmd, is there a way for me to style the window which opens up in scrcpy?

You can use the console tab to manually arrange the window. Run 'adb devices' to find out the connected devices and execute the command according to the scrcpy documentation for window arrangement.

List of devices attached
0123456789abcdef	device
192.168.1.1:5555	device

scrcpy -s 0123456789abcdef --window-title='My device'
// or 
scrcpy -s 192.168.1.1:5555 --window-x=100 --window-y=100 --window-width=800 --window-height=600
